services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build:
      context: node
    container_name: app
    volumes:
      - ./node:/app
      - /app/node_modules
    tty: true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - node-network
    command: sh -c "npm install && node index.js"

  db:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    networks:
      - node-network
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: desafio2
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  node-network:
    driver: bridge
